function [hitMetrics, intersectMetrics, onsetMetrics, timeMetrics] = ...
             getPerformanceMetrics(expertEvents, events, frames, srate, params)

%  Written by:  John La Rocco and Kay Robbins, UTSA, 2016-2017
params = processParameters('getPerformanceMetrics', ...
                       nargin, 4, params, getGeneralDefaults());
totalTime = (frames - 1)/srate;
%% Compute the different types of metrics given the 
hitConfusion = getConfusionHits(expertEvents, events, totalTime);
hitMetrics = getConfusionMetrics(hitConfusion.tp,  ...
                 hitConfusion.tn, hitConfusion.fp, hitConfusion.fn);
onsetConfusion = getConfusionOnsets(expertEvents, events, ...
                 totalTime, params.onsetTolerance, ...
                 params.spindleSecondsDuration);
onsetMetrics = getConfusionMetrics(onsetConfusion.tp, ...
               onsetConfusion.tn, onsetConfusion.fp, onsetConfusion.fn);
timeConfusion = getConfusionTimes(expertEvents, events, frames, ...
               srate, params.timingTolerance);
timeMetrics = getConfusionMetrics(timeConfusion.tp,...
               timeConfusion.tn, timeConfusion.fp, timeConfusion.fn);
intersectConfusion = getConfusionIntersects(expertEvents, events, ...
               totalTime, params.intersectTolerance, ...
               params.spindleSecondsDuration);
intersectMetrics = getConfusionMetrics(intersectConfusion.tp, ...
    intersectConfusion.tn,  intersectConfusion.fp, intersectConfusion.fn);

